import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import LocalFont from 'next/font/local'
import { NextFont } from "next/dist/compiled/@next/font";
import Nav from "@/components/navbar/nav";

export const metadata: Metadata = {
  title: "setareh",
  description: "Generated by create next app",
};

const vazir: NextFont=LocalFont({
  src:'../public/fonts/YekanBakhFaNum-Regular.woff2'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazir.className} min-h-screen bg-slate-50  flex flex-col `}>
        <header><Nav /></header>
        <main className=" flex-grow ">{children}</main>
        <footer className=" ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
